import type { ComfyApiNode, ComfyApiPrompt } from "./comfy-client.js";
import type { ImageJobReferenceInput } from "./image-job-repository.js";
import type {
  AnimaEngineSettings,
  EngineLoraSettings,
  ImageEditEngineSettings,
  KreaEngineSettings,
} from "./runtime-settings.js";

export const IMAGE_EDIT_MAX_REFERENCES = 4;
export const QWEN_IMAGE_EDIT_MAX_REFERENCES = 3;
export const MINIMAX_H3_IMAGE_MAX_REFERENCES = 9;
export const MINIMAX_H3_IMAGE_STEPS = [8, 12, 20, 30] as const;
export const MINIMAX_H3_IMAGE_MEGAPIXELS = [0.5, 0.7, 0.98, 2] as const;
export const IMAGE_API_MAX_PIXELS = 4_000_000;
export const IMAGE_UI_TARGET_MAX_PIXELS = 2_000_000;
export type MiniMaxH3ImageStepCount = (typeof MINIMAX_H3_IMAGE_STEPS)[number];
export type MiniMaxH3ImageMegapixels = (typeof MINIMAX_H3_IMAGE_MEGAPIXELS)[number];
export type MiniMaxH3ImageSettings = {
  model: string;
  encoder: string;
  vae: string;
  turboLora: string;
  turboStrength: number;
  detailLora: string;
  detailStrength: number;
  preserveStrength: number;
  steps: MiniMaxH3ImageStepCount;
  loras: EngineLoraSettings[];
};
export type QwenImageEditSettings = {
  model: string;
  encoder: string;
  vae: string;
  acceleratorLora: string;
  acceleratorStrength: number;
  steps: number;
  cfg: number;
  shift: number;
  referenceMegapixels: number;
};
export const DEFAULT_QWEN_IMAGE_EDIT_SETTINGS: QwenImageEditSettings = {
  model: "qwenImageEdit2511_fp8.safetensors",
  encoder: "qwen_2.5_vl_7b_fp8_scaled.safetensors",
  vae: "qwen_image_vae.safetensors",
  acceleratorLora: "Qwen-Image-Edit-2511-Lightning-4steps-V1.0-bf16.safetensors",
  acceleratorStrength: 1,
  steps: 4,
  cfg: 1,
  shift: 3.1,
  referenceMegapixels: 1.5,
};
export const DEFAULT_MINIMAX_H3_IMAGE_SETTINGS: Omit<MiniMaxH3ImageSettings, "model"> = {
  encoder: "qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors",
  vae: "minimax_h3_t1_image_vae_step1597.safetensors",
  turboLora: "minimax_h3_fl2v_turbo_8step_v1.0_comfyui_bf16.safetensors",
  turboStrength: 0.75,
  detailLora: "MaxiMin-HHH-R2V-ThisIsFine_LoRA_V0_1.safetensors",
  detailStrength: 0.5,
  preserveStrength: 0.6,
  steps: 20,
  loras: [],
};
const KREA_REBALANCE_WEIGHTS =
  "1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.5,5.0,1.1,4.0,1.0";
const ANIMA_NEGATIVE_PROMPT =
  "worst quality, low quality, score_1, score_2, score_3, blurry, jpeg artifacts, sepia";
const REFERENCE_ROLE_LABELS: Record<ImageJobReferenceInput["role"], string> = {
  base: "base image",
  subject: "subject",
  style: "style",
  pose: "pose",
  background: "background",
  other: "additional reference",
};

function node(
  classType: string,
  inputs: Record<string, unknown>,
  title: string,
): ComfyApiNode {
  return { class_type: classType, inputs, _meta: { title } };
}

function loadImageName(file: string) {
  // ComfyUI uses the annotation to resolve files outside its input folder.
  // Removing it makes an image generated by H3 Studio impossible to reuse as
  // an Edit reference because LoadImage falls back to the input directory.
  return file.trim().replaceAll(String.fromCharCode(92), "/");
}

function cloneTemplate(template?: ComfyApiPrompt): ComfyApiPrompt {
  return template ? JSON.parse(JSON.stringify(template)) as ComfyApiPrompt : {};
}

export function assertImageDimensions(width: number, height: number) {
  if (
    !Number.isInteger(width) ||
    !Number.isInteger(height) ||
    width < 64 ||
    height < 64 ||
    width > 4096 ||
    height > 4096 ||
    width % 16 !== 0 ||
    height % 16 !== 0
  ) {
    throw new Error("Larghezza e altezza devono essere multipli di 16 fra 64 e 4096");
  }
  if (width * height > IMAGE_API_MAX_PIXELS) {
    throw new Error("La risoluzione immagine non può superare 4 megapixel");
  }
}

export function buildKreaGeneratePrompt(input: {
  prompt: string;
  seed: number;
  width: number;
  height: number;
  filenamePrefix: string;
  settings: KreaEngineSettings;
  template?: ComfyApiPrompt;
}): ComfyApiPrompt {
  assertImageDimensions(input.width, input.height);
  const apiPrompt: ComfyApiPrompt = cloneTemplate(input.template);
  // Rebuild the output path of the selected Krea blueprint with validated
  // runtime values while preserving any compatible extra nodes.
  for (const id of ["8", "9", "10", "11", "40", "41", "42", "43"]) {
    delete apiPrompt[id];
  }
  Object.assign(apiPrompt, {
    "1": node(
      "UNETLoader",
      { unet_name: input.settings.model, weight_dtype: "default" },
      "Krea image model",
    ),
    "2": node(
      "CLIPLoader",
      { clip_name: input.settings.encoder, type: "krea2", device: "default" },
      "Krea text encoder",
    ),
    "3": node("VAELoader", { vae_name: input.settings.vae }, "Krea VAE"),
    "4": node(
      "CLIPTextEncode",
      { text: input.prompt, clip: ["2", 0] },
      "Image prompt",
    ),
    "5": node(
      "ConditioningKrea2Rebalance",
      {
        conditioning: ["4", 0],
        multiplier: 3,
        per_layer_weights: KREA_REBALANCE_WEIGHTS,
      },
      "Krea conditioning rebalance",
    ),
    "6": node(
      "ConditioningZeroOut",
      { conditioning: ["4", 0] },
      "Zero negative conditioning",
    ),
    "7": node(
      "EmptyLatentImage",
      { width: input.width, height: input.height, batch_size: 1 },
      "Image canvas",
    ),
  });
  let modelInput: [string, number] = ["1", 0];
  input.settings.loras.forEach((lora, index) => {
    const id = String(20 + index);
    apiPrompt[id] = node(
      "LoraLoaderModelOnly",
      {
        model: modelInput,
        lora_name: lora.name,
        strength_model: lora.strength,
      },
      `Krea LoRA ${index + 1}`,
    );
    modelInput = [id, 0];
  });
  apiPrompt["40"] = node(
    "KSampler",
    {
      model: modelInput,
      seed: input.seed,
      steps: input.settings.steps,
      cfg: 1,
      sampler_name: "er_sde",
      scheduler: "simple",
      positive: ["5", 0],
      negative: ["6", 0],
      latent_image: ["7", 0],
      denoise: 1,
    },
    "Krea image sampler",
  );
  apiPrompt["41"] = node(
    "VAEDecode",
    { samples: ["40", 0], vae: ["3", 0] },
    "Decode image",
  );
  apiPrompt["42"] = node(
    "ImageSharpenKJ",
    { image: ["41", 0], method: "rcas", "method.strength": 0.55 },
    "Image detail recovery",
  );
  apiPrompt["43"] = node(
    "SaveImage",
    { images: ["42", 0], filename_prefix: input.filenamePrefix },
    "Save generated image",
  );
  return apiPrompt;
}

export function buildAnimaGeneratePrompt(input: {
  prompt: string;
  seed: number;
  width: number;
  height: number;
  filenamePrefix: string;
  settings: AnimaEngineSettings;
  template?: ComfyApiPrompt;
}): ComfyApiPrompt {
  assertImageDimensions(input.width, input.height);
  const apiPrompt: ComfyApiPrompt = cloneTemplate(input.template);
  // The bundled Anima blueprint is authoritative and deliberately core-only.
  for (const id of Object.keys(apiPrompt)) delete apiPrompt[id];
  Object.assign(apiPrompt, {
    "1": node(
      "UNETLoader",
      { unet_name: input.settings.model, weight_dtype: "default" },
      "Anima image model",
    ),
    "2": node(
      "CLIPLoader",
      { clip_name: input.settings.encoder, type: "stable_diffusion", device: "default" },
      "Anima text encoder",
    ),
    "3": node("VAELoader", { vae_name: input.settings.vae }, "Anima VAE"),
    "4": node(
      "CLIPTextEncode",
      { text: input.prompt, clip: ["2", 0] },
      "Anima prompt",
    ),
    "5": node(
      "CLIPTextEncode",
      { text: ANIMA_NEGATIVE_PROMPT, clip: ["2", 0] },
      "Anima negative prompt",
    ),
    "6": node(
      "EmptyLatentImage",
      { width: input.width, height: input.height, batch_size: 1 },
      "Anima canvas",
    ),
  });
  let modelInput: [string, number] = ["1", 0];
  input.settings.loras.forEach((lora, index) => {
    const id = String(20 + index);
    apiPrompt[id] = node(
      "LoraLoaderModelOnly",
      {
        model: modelInput,
        lora_name: lora.name,
        strength_model: lora.strength,
      },
      `Anima LoRA ${index + 1}`,
    );
    modelInput = [id, 0];
  });
  apiPrompt["40"] = node(
    "KSampler",
    {
      model: modelInput,
      seed: input.seed,
      steps: input.settings.steps,
      cfg: input.settings.cfg,
      sampler_name: "euler",
      scheduler: "simple",
      positive: ["4", 0],
      negative: ["5", 0],
      latent_image: ["6", 0],
      denoise: 1,
    },
    "Anima sampler",
  );
  apiPrompt["41"] = node(
    "VAEDecode",
    { samples: ["40", 0], vae: ["3", 0] },
    "Decode Anima image",
  );
  apiPrompt["42"] = node(
    "SaveImage",
    { images: ["41", 0], filename_prefix: input.filenamePrefix },
    "Save Anima image",
  );
  return apiPrompt;
}

export function buildMiniMaxH3ImagePrompt(input: {
  prompt: string;
  seed: number;
  width: number;
  height: number;
  filenamePrefix: string;
  settings: MiniMaxH3ImageSettings;
  references: ImageJobReferenceInput[];
  template?: ComfyApiPrompt;
}): ComfyApiPrompt {
  assertImageDimensions(input.width, input.height);
  if (input.references.length > MINIMAX_H3_IMAGE_MAX_REFERENCES) {
    throw new Error("Image H3 supporta al massimo 9 reference");
  }
  const apiPrompt: ComfyApiPrompt = cloneTemplate(input.template);
  for (const id of Object.keys(apiPrompt)) delete apiPrompt[id];

  apiPrompt["1"] = node(
    "UNETLoader",
    { unet_name: input.settings.model, weight_dtype: "default" },
    "MiniMax H3 shared image/video model",
  );
  let textModel: [string, number] = ["1", 0];
  input.settings.loras.forEach((lora, index) => {
    const id = String(40 + index);
    apiPrompt[id] = node(
      "LoraLoaderModelOnly",
      {
        model: textModel,
        lora_name: lora.name,
        strength_model: lora.strength,
      },
      `MiniMax H3 image LoRA ${index + 1}`,
    );
    textModel = [id, 0];
  });
  const turboEnabled = input.settings.steps === 8 && Boolean(input.settings.turboLora);
  if (turboEnabled) {
    apiPrompt["2"] = node(
      "LoraLoaderModelOnly",
      {
        model: textModel,
        lora_name: input.settings.turboLora,
        strength_model: input.settings.turboStrength,
      },
      "MiniMax H3 image Turbo",
    );
    textModel = ["2", 0];
  }
  let editModel = textModel;
  if (input.settings.detailLora) {
    apiPrompt["3"] = node(
      "LoraLoaderModelOnly",
      {
        model: editModel,
        lora_name: input.settings.detailLora,
        strength_model: input.settings.detailStrength,
      },
      "MiniMax H3 image edit detail adapter",
    );
    editModel = ["3", 0];
  }
  apiPrompt["4"] = node(
    "CLIPLoader",
    { clip_name: input.settings.encoder, type: "minimax", device: "default" },
    "MiniMax H3 text/vision encoder",
  );
  apiPrompt["5"] = node(
    "VAELoader",
    { vae_name: input.settings.vae },
    "MiniMax H3 T=1 image VAE",
  );

  const referenceInputs: Record<string, unknown> = {};
  input.references.forEach((reference, index) => {
    const id = String(20 + index);
    apiPrompt[id] = node(
      "LoadImage",
      { image: loadImageName(reference.file) },
      `MiniMax Picture ${index + 1}: ${reference.role}`,
    );
    referenceInputs[index === 0 ? "source_image" : `reference_image_${index + 1}`] = [id, 0];
  });
  const mode = input.references.length === 0
    ? "text_to_image (FL2VA)"
    : input.references.length === 1
      ? "image_to_image (FL2VA)"
      : "reference_edit (REF2VA)";
  const selectedModel = input.references.length === 0 ? textModel : editModel;
  const samplingProfile = input.settings.steps === 8
    ? "Turbo v1.0 | 8 steps"
    : input.settings.steps === 12
      ? "base speed | RES 12 steps"
      : input.settings.steps === 20
        ? "base quality | RES 20 steps"
        : "custom | use controls below";
  apiPrompt["10"] = node(
    "H3ImagePrepare",
    {
      clip: ["4", 0],
      mode,
      prompt: input.prompt,
      width: input.width,
      height: input.height,
      frame_preset: "single image | 1 frame (image VAE)",
      optimize_prompt: true,
      preserve_strength: input.settings.preserveStrength,
      source_fit: "crop_center",
      reference_size: "max_identity_2048",
      vae: ["5", 0],
      ...referenceInputs,
    },
    "MiniMax H3 T2I / I2I / Reference prepare",
  );
  apiPrompt["11"] = node(
    "H3ImageSamplingPreset",
    {
      model: selectedModel,
      sampling_profile: samplingProfile,
      ...(input.settings.steps === 30
        ? {
            custom_sampler: "res_multistep",
            custom_scheduler: "simple",
            custom_steps: 30,
            custom_denoise: 1,
            custom_shift_video: 12,
            custom_shift_audio: 3,
          }
        : {}),
    },
    "MiniMax H3 single-image recipe",
  );
  apiPrompt["12"] = node("RandomNoise", { noise_seed: input.seed }, "MiniMax image seed");
  apiPrompt["13"] = node(
    "BasicGuider",
    { model: ["11", 0], conditioning: ["10", 0] },
    "MiniMax image guider",
  );
  apiPrompt["14"] = node(
    "SamplerCustomAdvanced",
    {
      noise: ["12", 0],
      guider: ["13", 0],
      sampler: ["11", 1],
      sigmas: ["11", 2],
      latent_image: ["10", 1],
    },
    "MiniMax image sampler",
  );
  apiPrompt["15"] = node(
    "H3ImageDecode",
    { samples: ["14", 0], vae: ["5", 0] },
    "MiniMax exact T=1 decode",
  );
  apiPrompt["16"] = node(
    "H3ImageFrameSelector",
    {
      frames: ["15", 0],
      strategy: "decode_recommended",
      manual_index: 0,
      skip_first_frames: 0,
      candidate_start: 0,
      candidate_end: 1,
      similarity_weight: 0.35,
      top_k: 1,
      emit_candidate_batch: false,
      recommended_index: ["15", 3],
      ...(input.references.length ? { source_image: ["20", 0] } : {}),
    },
    "MiniMax single image output",
  );
  apiPrompt["17"] = node(
    "SaveImage",
    { images: ["16", 0], filename_prefix: input.filenamePrefix },
    "Save MiniMax H3 image",
  );
  return apiPrompt;
}

export function buildFlux2KleinEditPrompt(input: {
  prompt: string;
  seed: number;
  width: number;
  height: number;
  filenamePrefix: string;
  settings: ImageEditEngineSettings;
  loras?: EngineLoraSettings[];
  references: ImageJobReferenceInput[];
  template?: ComfyApiPrompt;
}): ComfyApiPrompt {
  assertImageDimensions(input.width, input.height);
  if (input.references.length < 1 || input.references.length > IMAGE_EDIT_MAX_REFERENCES) {
    throw new Error("Flux.2 Klein Edit richiede da 1 a 4 reference");
  }
  const referenceMap = input.references
    .map((reference, index) =>
      "Image " + (index + 1) + " = " +
      REFERENCE_ROLE_LABELS[reference.role] + " (" + reference.name + ")"
    )
    .join("; ");
  const editInstruction = input.prompt + "\n\nReference map: " + referenceMap + ".";
  const apiPrompt: ComfyApiPrompt = cloneTemplate(input.template);
  // Reference chains and optional accelerators are rebuilt for the requested
  // 1–4 inputs. Other nodes in a compatible selected blueprint are preserved.
  for (const id of ["10", "11", "60", "61", "62", "63", "70", "71", "72", "73", "74"]) {
    delete apiPrompt[id];
  }
  for (let id = 20; id <= 39; id += 1) delete apiPrompt[String(id)];
  Object.assign(apiPrompt, {
    "1": node(
      "UNETLoader",
      { unet_name: input.settings.model, weight_dtype: "default" },
      "Flux.2 Klein 4B Distilled FP8",
    ),
    "2": node(
      "CLIPLoader",
      { clip_name: input.settings.encoder, type: "flux2", device: "default" },
      "Flux.2 Klein text encoder",
    ),
    "3": node("VAELoader", { vae_name: input.settings.vae }, "Flux.2 VAE"),
    "4": node(
      "CLIPTextEncode",
      { text: editInstruction, clip: ["2", 0] },
      "Edit instruction",
    ),
    "5": node(
      "ConditioningZeroOut",
      { conditioning: ["4", 0] },
      "Zero negative conditioning",
    ),
    "6": node(
      "EmptyFlux2LatentImage",
      { width: input.width, height: input.height, batch_size: 1 },
      "Flux.2 output canvas",
    ),
    "7": node("RandomNoise", { noise_seed: input.seed }, "Candidate noise"),
    "8": node("KSamplerSelect", { sampler_name: "euler" }, "Euler sampler"),
    "9": node(
      "Flux2Scheduler",
      { steps: input.settings.steps, width: input.width, height: input.height },
      "Flux.2 scheduler",
    ),
  });
  let guidedModel: [string, number] = ["1", 0];
  (input.loras ?? []).forEach((lora, index) => {
    const id = String(70 + index);
    apiPrompt[id] = node(
      "LoraLoaderModelOnly",
      {
        model: guidedModel,
        lora_name: lora.name,
        strength_model: lora.strength,
      },
      `Flux Edit LoRA ${index + 1}`,
    );
    guidedModel = [id, 0];
  });
  if (input.settings.attentionBackend !== "auto") {
    apiPrompt["11"] = node(
      "ModelAttentionBackend",
      {
        model: guidedModel,
        attention: input.settings.attentionBackend,
      },
      "Flux attention backend",
    );
    guidedModel = ["11", 0];
  }
  if (input.settings.kvCacheEnabled) {
    apiPrompt["10"] = node(
      "FluxKVCache",
      { model: guidedModel },
      "Flux reference KV cache",
    );
    guidedModel = ["10", 0];
  }

  let positive: [string, number] = ["4", 0];
  let negative: [string, number] = ["5", 0];
  const referenceMegapixels = 1;
  input.references.forEach((reference, index) => {
    const base = 20 + index * 5;
    const loadId = String(base);
    const scaleId = String(base + 1);
    const encodeId = String(base + 2);
    const positiveId = String(base + 3);
    const negativeId = String(base + 4);
    apiPrompt[loadId] = node(
      "LoadImage",
      { image: loadImageName(reference.file) },
      `Reference ${index + 1}: ${reference.role}`,
    );
    apiPrompt[scaleId] = node(
      "ImageScaleToTotalPixels",
      {
        image: [loadId, 0],
        upscale_method: "nearest-exact",
        megapixels: referenceMegapixels,
        resolution_steps: 1,
      },
      `Normalize reference ${index + 1}`,
    );
    apiPrompt[encodeId] = node(
      "VAEEncode",
      { pixels: [scaleId, 0], vae: ["3", 0] },
      `Encode reference ${index + 1}`,
    );
    apiPrompt[positiveId] = node(
      "ReferenceLatent",
      { conditioning: positive, latent: [encodeId, 0] },
      `Positive reference ${index + 1}`,
    );
    apiPrompt[negativeId] = node(
      "ReferenceLatent",
      { conditioning: negative, latent: [encodeId, 0] },
      `Negative reference ${index + 1}`,
    );
    positive = [positiveId, 0];
    negative = [negativeId, 0];
  });

  apiPrompt["60"] = node(
    "CFGGuider",
    {
      model: guidedModel,
      positive,
      negative,
      cfg: input.settings.cfg,
    },
    "Flux.2 guider",
  );
  apiPrompt["61"] = node(
    "SamplerCustomAdvanced",
    {
      noise: ["7", 0],
      guider: ["60", 0],
      sampler: ["8", 0],
      sigmas: ["9", 0],
      latent_image: ["6", 0],
    },
    "Flux.2 Klein edit sampler",
  );
  apiPrompt["62"] = node(
    "VAEDecode",
    { samples: ["61", 0], vae: ["3", 0] },
    "Decode edited image",
  );
  apiPrompt["63"] = node(
    "SaveImage",
    { images: ["62", 0], filename_prefix: input.filenamePrefix },
    "Save edited image",
  );
  return apiPrompt;
}

export function buildQwenImageEditPrompt(input: {
  prompt: string;
  seed: number;
  width: number;
  height: number;
  filenamePrefix: string;
  settings?: QwenImageEditSettings;
  loras?: EngineLoraSettings[];
  references: ImageJobReferenceInput[];
}): ComfyApiPrompt {
  assertImageDimensions(input.width, input.height);
  if (
    input.references.length < 1 ||
    input.references.length > QWEN_IMAGE_EDIT_MAX_REFERENCES
  ) {
    throw new Error("Qwen Image Edit richiede da 1 a 3 reference");
  }
  const settings = input.settings ?? DEFAULT_QWEN_IMAGE_EDIT_SETTINGS;
  const referenceMap = input.references
    .map((reference, index) =>
      "Image " + (index + 1) + " = " +
      REFERENCE_ROLE_LABELS[reference.role] + " (" + reference.name + ")"
    )
    .join("; ");
  const editInstruction = input.prompt + "\n\nReference map: " + referenceMap + ".";
  const apiPrompt: ComfyApiPrompt = {
    "1": node(
      "UNETLoader",
      { unet_name: settings.model, weight_dtype: "default" },
      "Qwen Image Edit 2511 FP8",
    ),
    "2": node(
      "CLIPLoader",
      { clip_name: settings.encoder, type: "qwen_image", device: "default" },
      "Qwen Image Edit text encoder",
    ),
    "3": node("VAELoader", { vae_name: settings.vae }, "Qwen Image VAE"),
    "4": node(
      "PathchSageAttentionKJ",
      {
        model: ["1", 0],
        sage_attention: "auto",
        allow_compile: false,
      },
      "Qwen automatic SageAttention",
    ),
  };

  let modelInput: [string, number] = ["4", 0];
  if (settings.acceleratorLora) {
    apiPrompt["5"] = node(
      "LoraLoaderModelOnly",
      {
        model: modelInput,
        lora_name: settings.acceleratorLora,
        strength_model: settings.acceleratorStrength,
      },
      "Qwen Image Edit 2511 Lightning",
    );
    modelInput = ["5", 0];
  }
  (input.loras ?? []).forEach((lora, index) => {
    const id = String(20 + index);
    apiPrompt[id] = node(
      "LoraLoaderModelOnly",
      {
        model: modelInput,
        lora_name: lora.name,
        strength_model: lora.strength,
      },
      `Qwen Edit LoRA ${index + 1}`,
    );
    modelInput = [id, 0];
  });
  apiPrompt["6"] = node(
    "ModelSamplingAuraFlow",
    { model: modelInput, shift: settings.shift },
    "Qwen sampling shift",
  );
  apiPrompt["7"] = node(
    "CFGNorm",
    { model: ["6", 0], strength: 1, pre_cfg: false },
    "Qwen CFG normalization",
  );

  const positiveInputs: Record<string, unknown> = {
    clip: ["2", 0],
    vae: ["3", 0],
    prompt: editInstruction,
  };
  const negativeInputs: Record<string, unknown> = {
    clip: ["2", 0],
    vae: ["3", 0],
    prompt: "low quality, blurry, compression artifacts",
  };
  input.references.forEach((reference, index) => {
    const loadId = String(30 + index * 2);
    const scaleId = String(31 + index * 2);
    apiPrompt[loadId] = node(
      "LoadImage",
      { image: loadImageName(reference.file) },
      `Qwen reference ${index + 1}: ${reference.role}`,
    );
    apiPrompt[scaleId] = node(
      "ImageScaleToTotalPixels",
      {
        image: [loadId, 0],
        upscale_method: "lanczos",
        megapixels: settings.referenceMegapixels,
        resolution_steps: 1,
      },
      `Normalize Qwen reference ${index + 1}`,
    );
    positiveInputs[`image${index + 1}`] = [scaleId, 0];
    negativeInputs[`image${index + 1}`] = [scaleId, 0];
  });
  apiPrompt["60"] = node(
    "TextEncodeQwenImageEditPlus",
    positiveInputs,
    "Qwen edit instruction",
  );
  apiPrompt["61"] = node(
    "TextEncodeQwenImageEditPlus",
    negativeInputs,
    "Qwen edit negative",
  );
  apiPrompt["62"] = node(
    "FluxKontextMultiReferenceLatentMethod",
    {
      conditioning: ["60", 0],
      reference_latents_method: "index_timestep_zero",
    },
    "Qwen positive reference method",
  );
  apiPrompt["63"] = node(
    "FluxKontextMultiReferenceLatentMethod",
    {
      conditioning: ["61", 0],
      reference_latents_method: "index_timestep_zero",
    },
    "Qwen negative reference method",
  );
  apiPrompt["64"] = node(
    "EmptySD3LatentImage",
    { width: input.width, height: input.height, batch_size: 1 },
    "Qwen output canvas",
  );
  apiPrompt["65"] = node(
    "KSampler",
    {
      model: ["7", 0],
      seed: input.seed,
      steps: settings.steps,
      cfg: settings.cfg,
      sampler_name: "euler",
      scheduler: "simple",
      positive: ["62", 0],
      negative: ["63", 0],
      latent_image: ["64", 0],
      denoise: 1,
    },
    "Qwen Image Edit sampler",
  );
  apiPrompt["66"] = node(
    "VAEDecode",
    { samples: ["65", 0], vae: ["3", 0] },
    "Decode Qwen edit",
  );
  apiPrompt["67"] = node(
    "SaveImage",
    { images: ["66", 0], filename_prefix: input.filenamePrefix },
    "Save Qwen edit",
  );
  return apiPrompt;
}
